# example netlify.toml
[build]
  functions = "netlify/functions"
  publish = "."

[dev]
  autoLaunch = false

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@sparticuz/chromium"]
  myFunction = { timeout = 60 }